### ISSUE TITLE
createStoredProcedure() in your example doesn't exist in DocumentDbUtility

### ISSUE THREAD

**Issue by lumberbeard** [spatney/documentdb-util#2]
createStoredProcedure() in your example doesn't exist in DocumentDbUtility and storedProcedure returns a bad request when you call it like you're trying in your documentation. Could this be updated?

Thanks,

Brian

**Comment by spatney** [comment]
Thanks. I'll look into this, and fix it.

**Comment by spatney** [comment]
I ran the sample, and it works fine. Also it isn't called createStoredProcedure() intentionally, since storedProcedure call either gets or creates a stored proc if one doesn't exist. Could it be possible you already have a stored proc with that name? and so its running that instead of creating what you intended? A code sample of what you are doing would help.

**Comment by spatney** [comment]
closing due to lack of a response.
